name: 🚀 Auto Deploy to Server

on:
  push:
    branches:
      - main   # Change if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            npm install --production    # or pip install -r requirements.txt
            pm2 restart all             # or systemctl restart your-app
            echo "✅ Deployment complete!"
          EOF